import ts from "typescript";
import fs from "fs";
import path from "path";

const ENTRY = path.resolve("./src/infra/router.ts");
const OUT_DIR = path.resolve("./types");
const OUT_FILE = path.join(OUT_DIR, "client.d.ts");

const configPath = ts.findConfigFile("./", ts.sys.fileExists, "tsconfig.json");
if (!configPath) throw new Error("tsconfig.json not found");

const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, path.dirname(configPath));

const program = ts.createProgram(parsed.fileNames, parsed.options);
const checker = program.getTypeChecker();

const known_external_types = [
  ["BuiltRouter", "TRPCBuiltRouter"],
  ["DefaultErrorShape", "TRPCDefaultErrorShape"],
  ["DecorateCreateRouterOptions", "TRPCDecorateCreateRouterOptions"],
  ["QueryProcedure", "TRPCQueryProcedure"],
  ["MutationProcedure", "TRPCMutationProcedure"],
];

const sourceFile = program.getSourceFile(ENTRY);
if (!sourceFile) throw new Error(`Could not load ${ENTRY}`);

let imports: Map<string, Set<string>> = new Map(); // module -> names
let body = "";

function addImport(moduleName: string, typeName: string) {
  if (!imports.has(moduleName)) imports.set(moduleName, new Set());
  imports.get(moduleName)!.add(typeName);
}

function serializeSymbol(symbol: ts.Symbol): string {
  return checker.symbolToString(symbol);
}

function serializeType(type: ts.Type): string {
  return checker.typeToString(type, undefined, ts.TypeFormatFlags.NoTruncation);
}

// --- Walk exports ---
const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
if (moduleSymbol) {
  const exports = checker.getExportsOfModule(moduleSymbol);
  for (const exp of exports) {
    const name = serializeSymbol(exp);
    const decl = exp.valueDeclaration ?? exp.declarations?.[0];
    if (!decl) continue;
    const type = checker.getTypeOfSymbolAtLocation(exp, decl);
    const typeStr = serializeType(type);

    if (ts.isVariableDeclaration(decl)) {
      body += `export declare const ${name}: ${typeStr};\n\n`;
    } else if (ts.isFunctionDeclaration(decl)) {
      body += `export declare function ${name}${typeStr};\n\n`;
    } else if (exp.declarations?.some(d => ts.isInterfaceDeclaration(d) || ts.isTypeAliasDeclaration(d))) {
      for (const d of exp.declarations) {
        const declaration = d.getText(sourceFile);
        if (declaration.includes('export')) {
          body += `${declaration}\n\n`;
        } else {
          body += `export ${declaration}\n\n`;
        }
      }
    } else {
      body += `export declare const ${name}: ${typeStr};\n\n`;
    }
  }
}

// --- Build final output ---
let output = `// Auto-generated by generateClientTypes.ts\n`;

for (const [_from, to] of known_external_types) {
  addImport("@trpc/server", to);
}

for (const [mod, names] of imports) {
  output += `import { ${Array.from(names).join(", ")} } from "${mod}";\n`;
}

output += `\n${body}`;

for (const [from, to] of known_external_types) {
  const regex = new RegExp(`\\b${from}\\b`, "g");
  output = output.replace(regex, to);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, output.trim(), "utf8");

console.log(`✅ Types written to ${OUT_FILE}`);
